### ISSUE TITLE
Inconsistency in the field `envs` for secretGenerator between the CLI and this pkg

### ISSUE THREAD

**Issue by manute** [kubernetes/cli-runtime#16]
Hello, 

It seems that the latest version of kustomize CLI (`3.8.2`) requires for the field `envs` in a `secretGenerator` a list of the possibles files.  And the latest version of this pkg,  requires for that field, the property `env` with a string.

It would be nice if  this pkg is aligned with the cli, and I can work on a PR if that's ok.

**Comment by nikhita** [comment]
cc @seans3

**Comment by monopole** [comment]
The `env` field was deprecated in May of 2019, and removed in Oct 2019  ( https://github.com/kubernetes-sigs/kustomize/pull/1637 ). It was replaced by `envs`, since the field is a list (an api fix).
It will be fixed in kubectl when https://github.com/kubernetes-sigs/kustomize/issues/1500 closes.

**Comment by manute** [comment]
Thanks for the info, I was referrering to the inconsistency  running this (with `k8s.io/cli-runtime v0.19.0`) -> 
```golang

import "k8s.io/cli-runtime/pkg/kustomize"
..

kustomize.RunKustomizeBuild(...)
```
Because it's failing for the field `envs` and only accepts `env`, and on the other hand the kustomize CLI (3.8.2) it's using the correct  field `envs`.

So I'm not completely sure that the issue you mentioned will fix this.

**Comment by monopole** [comment]
This will only be fixed (in kubectl) by closing  kubernetes-sigs/kustomize#1500 (targetting next release, march 2021)

/close
