### ISSUE TITLE
cannot find "sigs.k8s.io/kustomize/pkg/factory"

### ISSUE THREAD

**Issue by giddel** [kubernetes/cli-runtime#2]
The dependency "sigs.k8s.io/kustomize/pkg/factory" does not exists.

If I do a `go get ./...` in my project I get: 
` cannot find package "sigs.k8s.io/kustomize/pkg/factory"`

my Intellj Idea explains:
`../k8s.io/cli-runtime/pkg/kustomize/k8sdeps/factory.go:24:2: cannot find package "sigs.k8s.io/kustomize/pkg/factory"`

Thats right, it was deleted: https://github.com/kubernetes-sigs/kustomize/pull/784/commits/bce894a5a04be344695c46447062804ace84b886

I deleted my complete `$GOROOT/src/k8s.io` and `$GOROOT/src/sigs.k8s.io` directories and re-run the `go get`  - it did not help

The cli-runtime is pulled  in as sub-dependency by any other package I use for my development., not by my own. How should I deal with this?

**Comment by tklebanoff** [comment]
I have this same problem. does anybody have a solution?

**Comment by liggitt** [comment]
See comment at https://github.com/kubernetes/kubernetes/issues/77502#issuecomment-489627729 for determining the correct level of the kustomize library to use

/close
