### ISSUE TITLE
cannot find kubernetes-1.11.0-alpha.2 tag of repo k8s.io/cli-runtime

### ISSUE THREAD

**Issue by markzhang0928** [kubernetes/cli-runtime#4]
dear approvers and reviewers of k8s, @caesarxuchao @sttts @dims @mfojtik @nikhita 

I am using Client-go(v8.0.0) to develop some debug-tools for our k8s platform, while it relys on the library of `k8s.io/cli-runtime` when I built, but the version of kubernetes-1.11.x of [this repo](https://github.com/kubernetes/cli-runtime/tree/kubernetes-1.11.0-alpha.2) is empty. 

I follow the guide and find your contact info on there.  Then, I wonder if I should submit a PR on staging directory or just call you members for help.

```
If further repos under staging are need, adding them to the bot is easy. Contact one of the [owners of the bot](https://github.com/kubernetes/publishing-bot/blob/master/OWNERS).
```

some references info listed below:
```
# github.com/huya/huyactl-debug/vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource
../../vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/helper.go:111:85: undefined: "github.com/huya/huyactl-debug/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions
../../vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/helper.go:113:14: undefined: "github.com/huya/huyactl-debug/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions
../../vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/helper.go:132:104: undefined: "github.com/huya/huyactl-debug/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions
../../vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/helper.go:141:90: undefined: "github.com/huya/huyactl-debug/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".UpdateOptions
../../vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/helper.go:143:14: undefined: "github.com/huya/huyactl-debug/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".UpdateOptions
```

go.mod 
```

replace (
	k8s.io/api => k8s.io/api v0.0.0-20181216230433-16e3e9a3868f
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.0.0-20181216234223-6a481390bade
	k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20181203235515-3d8ee2261517
	k8s.io/cli-runtime => k8s.io/cli-runtime v0.0.0-20181004125037-79bf4e0b6454
	k8s.io/client-go => k8s.io/client-go v8.0.0+incompatible
)
```

**Comment by nikhita** [comment]
@markzhang0928 cli-runtime was created in 1.12, so using 1.11 tag for cli-runtime won't work.  For using cli-runtime, you'll need to use the 1.12 tags and client-go v9.0.0.

Having said that, the bot shouldn't have published the 1.11 tags in the first place. Looks like the bot publishes all tags for all repos regardless of the rules - https://github.com/kubernetes/node-api/tree/kubernetes-1.9.0-alpha.0.

That's a bug. Will look into it.

**Comment by markzhang0928** [comment]
thank you for your reply.  

I copied the code with license and solve my problem.

**Comment by nikhita** [comment]
@markzhang0928 Thanks again for the bug report! :+1: 

I've referenced this in https://github.com/kubernetes/publishing-bot/issues/195 for easier tracking so I'll close this issue.
